# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install serverless
        run: npm install -g serverless@3.38.0
      - name: Set serverless config
        run: serverless config credentials --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_ACCESS_SECRET }} --provider aws --overwrite
      - name: Install npm dependencies
        working-directory: ./notes-backend
        run: npm install
      - name: Deploy service
        working-directory: ./notes-backend
        run: serverless deploy --region eu-west-1 --verbose
      - name: Install frontend npm dependencies
        working-directory: ./notes-frontend
        run: npm install --legacy-peer-deps
      - name: Build frontend app
        working-directory: ./notes-frontend
        run: npm run build
      - uses: shallwefootball/s3-upload-action@master
        name: upload to s3
        with:
            aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_ACCESS_SECRET }}
            aws_bucket: soulandmindconsultant.com
            source_dir: ./notes-frontend/public